# NumPy
NumPy is a Python library used for working with arrays. NumPy also has functions to help working in domain of linear algebra, fourier transform, and matrices.

In [2]:
import numpy as np

## Creating NumPy Arrays
### From a Python List
We can create an array by converting a list to an array

In [3]:
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods
There are many ways to generate an arrays

In [7]:
# arange
# it will make an array with the specified number within a given interval

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
# zeros and ones
# generates arrays of zeros or ones

np.zeros(3)

array([0., 0., 0.])

In [11]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [19]:
# linspace
# it will return evenly spaced numbers over a specified interval

np.linspace(0,10,5)

# .linspace() includes the stop value, to get an array with common fractions 
# increas the number of items

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
# eye
# it will creates an identity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random
NumPy has a function that allow you to create random number arrays

In [22]:
# rand
# creates an array of the given shapes with random samples from a uniform
# distribution over 0-100

np.random.rand(5,5)

array([[0.03694422, 0.16087233, 0.92478075, 0.01644548, 0.75292235],
       [0.15857309, 0.0185649 , 0.52380888, 0.81335736, 0.73466086],
       [0.9089915 , 0.40469179, 0.62056655, 0.45934441, 0.11027816],
       [0.70417234, 0.47950203, 0.65841042, 0.85661721, 0.16576833],
       [0.07655772, 0.67223547, 0.58292559, 0.12818079, 0.67353207]])

In [23]:
# randn
# return a sample from the standard normal distribution [σ = 1]

np.random.randn(5)

array([ 0.5389106 , -2.17330896,  1.18099231, -2.84066254, -0.18090439])

In [25]:
# randint
# retrun random integers from low to high

np.random.randint(1,50, 10)

array([16, 15, 45, 18, 40, 20, 44, 32, 40, 37])